export const FETCH_AUTHORS_SUCCESS = "FETCH_AUTHORS_SUCCESS";
export const FETCH_AUTHOR_BY_ID_SUCCESS = "FETCH_AUTHOR_BY_ID_SUCCESS";
export const ADD_AUTHOR_SUCCESS = "ADD_AUTHOR_SUCCESS";
export const DELETE_AUTHOR_SUCCESS = "DELETE_AUTHOR_SUCCESS";

export const AUTHORS_LOADİNG = "AUTHORS_LOADING";
export const AUTHORS_ERROR = "AUTHORS_ERROR";