export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";
export const FETCH_BOOK_BY_ID_SUCCESS = "FETCH_BOOK_BY_ID_SUCCESS";
export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS";
export const UPDATE_BOOK_SUCCESS = "UPDATE_BOOK_SUCCESS";
export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";

export const BOOKS_LOADING = "BOOKS_LOADING";
export const BOOKS_ERROR = "BOOKS_ERROR";