export const FETCH_CUSTOMERS_SUCCESS = "FETCH_CUSTOMERS_SUCCESS";
export const FETCH_CUSTOMER_BY_ID_SUCCESS = "FETCH_CUSTOMER_BY_ID_SUCCESS";
export const ADD_CUSTOMER_SUCCESS = "ADD_CUSTOMER_SUCCESS";
export const UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCCESS";
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS";

export const CUSTOMERS_LOADING = "CUSTOMERS_LOADING";
export const CUSTOMERS_ERROR = "CUSTOMERS_ERROR";